(function() {var implementors = {};
implementors['atom_syndication'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Author.html' title='atom_syndication::Author'>Author</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Category.html' title='atom_syndication::Category'>Category</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Contributor.html' title='atom_syndication::Contributor'>Contributor</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Entry.html' title='atom_syndication::Entry'>Entry</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Feed.html' title='atom_syndication::Feed'>Feed</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Generator.html' title='atom_syndication::Generator'>Generator</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Link.html' title='atom_syndication::Link'>Link</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Person.html' title='atom_syndication::Person'>Person</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='atom_syndication/struct.Source.html' title='atom_syndication::Source'>Source</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
